-- MySQL Script generated by MySQL Workbench
-- Τρι 17 Απρ 2018 11:33:38 μμ EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema linkedin_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema linkedin_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `linkedin_db` DEFAULT CHARACTER SET utf8 ;
USE `linkedin_db` ;

-- -----------------------------------------------------
-- Table `linkedin_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linkedin_db`.`user` (
  `iduser` INT NOT NULL,
  `password_hashed` VARCHAR(128) NOT NULL,
  `first_name` VARCHAR(128) NOT NULL,
  `last_name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `phone_number` VARCHAR(128) NOT NULL,
  `photo_path` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
